# Generated by Django 4.1.6 on 2023-06-21 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pasillo', models.CharField(max_length=20)),
                ('seccion', models.CharField(max_length=20)),
                ('altura', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['pasillo', 'seccion', 'altura'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('cif', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('web', models.URLField()),
            ],
            options={
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='FilaVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_venta', models.IntegerField()),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('precio_minorista', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_mayorista', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fotografia', models.ImageField(upload_to='productos/')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('cif', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('web', models.URLField()),
            ],
            options={
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.cliente')),
                ('id_producto', models.ManyToManyField(through='API.FilaVenta', to='API.producto')),
                ('id_usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.almacen'),
        ),
        migrations.AddField(
            model_name='filaventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.producto'),
        ),
        migrations.AddField(
            model_name='filaventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.venta'),
        ),
        migrations.CreateModel(
            name='FilaDevolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_devuelta', models.IntegerField()),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.devolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='devolucion',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.venta'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.producto')),
                ('id_usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
